python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_64.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_128.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_256.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_512.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_1024.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_64.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_128.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_256.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_512.json
python seq2seq.py --gpu=6 --config=configs/attention_tune_emb/emb_1024.json
